import { db, productsTable } from "@workspace/db";

const products = [
  // SHOES (10)
  { name: "Air Force Lagos", description: "Iconic white low-top sneaker with premium leather upper and cushioned sole. A street staple.", category: "shoes", price: 45000, stock: 40, colors: ["White", "Black"], productType: "Sneaker", tags: ["trending", "casual"], imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80" },
  { name: "Ankara Print Slides", description: "Bold Ankara-patterned slides with a thick EVA sole. Comfortable and culturally rich.", category: "shoes", price: 12000, stock: 60, colors: ["Multi"], productType: "Slides", tags: ["summer", "local"], imageUrl: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800&q=80" },
  { name: "Classic Oxford Brogues", description: "Full-grain leather brogues perfect for corporate and formal occasions.", category: "shoes", price: 58000, stock: 30, colors: ["Brown", "Black"], productType: "Formal", tags: ["formal", "office"], imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&q=80" },
  { name: "Suede Chelsea Boots", description: "Slip-on suede Chelsea boots with elastic side panels and a chunky rubber sole.", category: "shoes", price: 67000, stock: 25, colors: ["Tan", "Black", "Navy"], productType: "Boots", tags: ["winter", "premium"], imageUrl: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80" },
  { name: "Lagos Runner Pro", description: "Lightweight running shoe with breathable mesh upper and responsive foam midsole.", category: "shoes", price: 38000, stock: 50, colors: ["Black/Red", "Grey/Blue"], productType: "Running", tags: ["sport", "gym"], imageUrl: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80" },
  { name: "Woven Raffia Sandals", description: "Handcrafted Nigerian raffia sandals with leather straps. Breathable and eco-friendly.", category: "shoes", price: 9500, stock: 45, colors: ["Natural", "Black"], productType: "Sandals", tags: ["local", "eco"], imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80" },
  { name: "High-Top Canvas", description: "Classic canvas high-top sneakers with vulcanized rubber sole. Timeless street style.", category: "shoes", price: 22000, stock: 55, colors: ["White", "Black", "Red"], productType: "Sneaker", tags: ["casual", "classic"], imageUrl: "https://images.unsplash.com/photo-1494496195158-c3bc9ad97512?w=800&q=80" },
  { name: "Platform Loafers", description: "Chunky platform loafers in smooth faux leather with gold hardware detailing.", category: "shoes", price: 31000, stock: 35, colors: ["Beige", "Black"], productType: "Loafers", tags: ["fashion", "statement"], imageUrl: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80" },
  { name: "Satin Kitten Heels", description: "Elegant satin kitten heels with pointed toe. Perfect for events and evening wear.", category: "shoes", price: 27500, stock: 30, colors: ["Nude", "Black", "Wine"], productType: "Heels", tags: ["elegant", "evening"], imageUrl: "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=800&q=80" },
  { name: "Trail Hiking Boots", description: "Waterproof hiking boots with grippy Vibram outsole and ankle support.", category: "shoes", price: 75000, stock: 20, colors: ["Brown", "Olive"], productType: "Boots", tags: ["outdoor", "adventure"], imageUrl: "https://images.unsplash.com/photo-1520219306100-ec4afeeefe58?w=800&q=80" },

  // APPAREL (10)
  { name: "Agbada Royale Set", description: "Three-piece embroidered Agbada in premium Aso-oke fabric. Perfect for ceremonies.", category: "apparel", price: 85000, stock: 15, colors: ["Royal Blue", "Gold", "White"], productType: "Traditional", tags: ["aso-ebi", "ceremony"], imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80" },
  { name: "Ankara Midi Dress", description: "Vibrant Ankara wax-print midi dress with puff sleeves and side pockets.", category: "apparel", price: 18500, stock: 40, colors: ["Multi"], productType: "Dress", tags: ["ankara", "summer"], imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=80" },
  { name: "Linen Buba & Sokoto", description: "Relaxed linen Buba and Sokoto set in natural earth tones. Cool and breathable.", category: "apparel", price: 22000, stock: 35, colors: ["Cream", "Sky Blue", "Olive"], productType: "Traditional", tags: ["casual", "local"], imageUrl: "https://images.unsplash.com/photo-1607522370275-f6fd0d76c4cc?w=800&q=80" },
  { name: "Oversized Graphic Tee", description: "100% cotton oversized tee with Lagos-inspired graphic print. Streetwear essential.", category: "apparel", price: 8500, stock: 80, colors: ["Black", "White", "Grey"], productType: "T-Shirt", tags: ["streetwear", "casual"], imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80" },
  { name: "Tailored Suit (3-piece)", description: "Slim-fit Italian-cut suit in wool-blend fabric. Includes jacket, trousers, and waistcoat.", category: "apparel", price: 120000, stock: 10, colors: ["Charcoal", "Navy", "Black"], productType: "Suit", tags: ["formal", "premium"], imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80" },
  { name: "Cargo Jogger Pants", description: "Multi-pocket cargo joggers in stretch cotton. Comfortable for all-day wear.", category: "apparel", price: 14000, stock: 60, colors: ["Olive", "Black", "Khaki"], productType: "Pants", tags: ["casual", "streetwear"], imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80" },
  { name: "Silk Wrap Blouse", description: "Flowy silk-effect wrap blouse with V-neckline and tie waist. Office-to-evening style.", category: "apparel", price: 16000, stock: 45, colors: ["Ivory", "Blush", "Emerald"], productType: "Top", tags: ["office", "elegant"], imageUrl: "https://images.unsplash.com/photo-1551163943-3f7fb896e0f5?w=800&q=80" },
  { name: "Denim Jacket Vintage", description: "Distressed vintage-wash denim jacket with raw hem and custom embroidery.", category: "apparel", price: 29500, stock: 30, colors: ["Light Blue", "Dark Blue"], productType: "Jacket", tags: ["vintage", "denim"], imageUrl: "https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?w=800&q=80" },
  { name: "Adire Tie-Dye Kaftan", description: "Hand-dyed Yoruba Adire kaftan in indigo and white. Comfortable and artistic.", category: "apparel", price: 13000, stock: 50, colors: ["Indigo/White"], productType: "Kaftan", tags: ["local", "adire", "cultural"], imageUrl: "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=800&q=80" },
  { name: "Hooded Trench Coat", description: "Classic double-breasted trench coat with detachable hood. Elegant all-weather layer.", category: "apparel", price: 95000, stock: 12, colors: ["Camel", "Black", "Olive"], productType: "Coat", tags: ["winter", "premium"], imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80" },

  // ELECTRONICS (10)
  { name: "ANC Wireless Headphones", description: "Active noise cancelling headphones with 40-hour battery life and premium audio drivers.", category: "electronics", price: 89000, stock: 20, colors: ["Black", "Silver"], productType: "Headphones", tags: ["audio", "wireless"], imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80" },
  { name: "Smart Watch Pro", description: "Health-tracking smartwatch with AMOLED display, GPS, heart rate and SpO2 sensor.", category: "electronics", price: 75000, stock: 25, colors: ["Black", "Rose Gold", "Silver"], productType: "Wearable", tags: ["health", "fitness"], imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80" },
  { name: "TWS Earbuds X7", description: "True wireless earbuds with 6-hour playtime, deep bass and IPX5 water resistance.", category: "electronics", price: 32000, stock: 50, colors: ["White", "Black"], productType: "Earbuds", tags: ["audio", "sport"], imageUrl: "https://images.unsplash.com/photo-1590658165737-15a047b7c35a?w=800&q=80" },
  { name: "65W Fast Charger Hub", description: "6-port USB-C hub with 65W PD fast charging, compatible with all major devices.", category: "electronics", price: 18500, stock: 60, colors: ["Black", "White"], productType: "Charger", tags: ["accessories", "charging"], imageUrl: "https://images.unsplash.com/photo-1609692814858-f7cd2f0afa4f?w=800&q=80" },
  { name: "Portable Bluetooth Speaker", description: "360° sound portable speaker with 24-hour battery and waterproof IPX7 rating.", category: "electronics", price: 41000, stock: 35, colors: ["Black", "Navy", "Red"], productType: "Speaker", tags: ["audio", "outdoor"], imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80" },
  { name: "Mechanical Keyboard TKL", description: "Tenkeyless mechanical keyboard with RGB backlight and tactile brown switches.", category: "electronics", price: 55000, stock: 20, colors: ["Black", "White"], productType: "Keyboard", tags: ["gaming", "productivity"], imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80" },
  { name: "4K Webcam Ultra", description: "4K autofocus webcam with built-in noise-cancelling mic. Perfect for remote work.", category: "electronics", price: 47000, stock: 25, colors: ["Black"], productType: "Webcam", tags: ["work", "streaming"], imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80" },
  { name: "Wireless Charging Pad", description: "15W Qi-certified wireless charging pad compatible with iPhone and Android.", category: "electronics", price: 12500, stock: 80, colors: ["Black", "White"], productType: "Charger", tags: ["charging", "wireless"], imageUrl: "https://images.unsplash.com/photo-1586495777744-4e6232bf2176?w=800&q=80" },
  { name: "Ring Light 18-inch", description: "Professional 18-inch LED ring light with tripod stand. Ideal for content creators.", category: "electronics", price: 28000, stock: 30, colors: ["White"], productType: "Lighting", tags: ["creator", "studio"], imageUrl: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80" },
  { name: "Portable Power Bank 20K", description: "20,000mAh slim power bank with dual USB-A and USB-C output. NEPA proof.", category: "electronics", price: 22000, stock: 70, colors: ["Black", "White"], productType: "Power Bank", tags: ["essential", "travel"], imageUrl: "https://images.unsplash.com/photo-1585338447937-7082f8fc763d?w=800&q=80" },

  // HOME (10)
  { name: "Linen Throw Pillow Set", description: "Set of 4 European linen throw pillows with removable covers. Minimalist aesthetic.", category: "home", price: 16000, stock: 40, colors: ["Beige", "Grey", "Terracotta"], productType: "Bedding", tags: ["decor", "bedroom"], imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80" },
  { name: "Woven Jute Area Rug 5x7", description: "Hand-woven natural jute area rug. Durable, eco-friendly and stylish.", category: "home", price: 38000, stock: 15, colors: ["Natural", "Grey"], productType: "Rug", tags: ["living room", "eco"], imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80" },
  { name: "Bamboo Desk Organiser", description: "6-compartment bamboo desk organiser to keep your workspace tidy and stylish.", category: "home", price: 9500, stock: 55, colors: ["Natural"], productType: "Storage", tags: ["office", "organisation"], imageUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80" },
  { name: "Terracotta Plant Pot Set", description: "Set of 3 handmade terracotta pots with saucers. Ideal for succulents and herbs.", category: "home", price: 11500, stock: 45, colors: ["Terracotta"], productType: "Garden", tags: ["plants", "decor"], imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80" },
  { name: "Scented Soy Candle Collection", description: "Pack of 3 hand-poured soy wax candles in Lagos Nights, Oud & Cedar, and Citrus Bloom scents.", category: "home", price: 14500, stock: 60, colors: ["Cream"], productType: "Candles", tags: ["aromatherapy", "gift"], imageUrl: "https://images.unsplash.com/photo-1602874801007-bd458bb1b8b6?w=800&q=80" },
  { name: "Smart LED Bulb Pack (4)", description: "4x 9W WiFi smart bulbs with 16M colours and app control. Works with Alexa and Google Home.", category: "home", price: 19000, stock: 35, colors: ["Multi"], productType: "Lighting", tags: ["smart home", "lighting"], imageUrl: "https://images.unsplash.com/photo-1563461660947-507ef49e9c47?w=800&q=80" },
  { name: "Cotton Waffle Blanket", description: "Lightweight 100% cotton waffle-knit blanket. Perfect for Nigeria's harmattan season.", category: "home", price: 21000, stock: 30, colors: ["White", "Stone", "Sage"], productType: "Bedding", tags: ["bedroom", "cosy"], imageUrl: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=800&q=80" },
  { name: "Floating Wall Shelves (3-pack)", description: "Set of 3 pine wood floating shelves with invisible brackets. Easy DIY install.", category: "home", price: 17500, stock: 25, colors: ["Natural", "White", "Walnut"], productType: "Furniture", tags: ["storage", "wall decor"], imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80" },
  { name: "Macramé Wall Hanging", description: "Hand-knotted bohemian macramé wall hanging. Large 90cm piece, natural cotton cord.", category: "home", price: 13000, stock: 20, colors: ["Natural"], productType: "Decor", tags: ["boho", "art"], imageUrl: "https://images.unsplash.com/photo-1576017316987-79c4bb92b1d3?w=800&q=80" },
  { name: "Blackout Curtain Pair", description: "100% blackout thermal curtains with eyelet headers. Reduces heat by 40%.", category: "home", price: 32000, stock: 30, colors: ["Charcoal", "Beige", "Navy"], productType: "Curtains", tags: ["bedroom", "living room"], imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80" },

  // KITCHEN (10)
  { name: "Cast Iron Skillet 12\"", description: "Pre-seasoned 12-inch cast iron skillet. Distributes heat evenly for perfect suya and eggs.", category: "kitchen", price: 28000, stock: 25, colors: ["Black"], productType: "Cookware", tags: ["cooking", "durable"], imageUrl: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&q=80" },
  { name: "5L Stainless Pressure Pot", description: "Heavy-duty stainless steel pressure pot. Cook egusi and beans in half the time.", category: "kitchen", price: 22000, stock: 35, colors: ["Silver"], productType: "Cookware", tags: ["cooking", "essential"], imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80" },
  { name: "Electric Blender 1500W", description: "High-powered blender with 1500W motor and 6 stainless blades. Blends pepper and tomatoes effortlessly.", category: "kitchen", price: 35000, stock: 40, colors: ["Silver/Black", "White"], productType: "Appliance", tags: ["blending", "cooking"], imageUrl: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&q=80" },
  { name: "Bamboo Cutting Board Set", description: "Set of 3 bamboo cutting boards in S, M, L sizes with juice grooves.", category: "kitchen", price: 12000, stock: 55, colors: ["Natural"], productType: "Prep", tags: ["eco", "prep"], imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80" },
  { name: "Ceramic Non-Stick Pan", description: "PFOA-free ceramic non-stick 28cm frying pan with soft-touch handle.", category: "kitchen", price: 18500, stock: 45, colors: ["Stone", "Sage", "Rust"], productType: "Cookware", tags: ["healthy", "non-stick"], imageUrl: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80" },
  { name: "Digital Kitchen Scale", description: "Precision 5kg digital kitchen scale with tare function. Accurate to 1g.", category: "kitchen", price: 8500, stock: 70, colors: ["Black", "White"], productType: "Tools", tags: ["baking", "precision"], imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80" },
  { name: "Glass Meal Prep Containers", description: "Set of 5 airtight borosilicate glass containers. Microwave, oven and freezer safe.", category: "kitchen", price: 19000, stock: 40, colors: ["Clear"], productType: "Storage", tags: ["meal prep", "storage"], imageUrl: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&q=80" },
  { name: "Coffee Maker Drip 12-Cup", description: "Programmable 12-cup drip coffee maker with keep-warm plate and auto-shutoff.", category: "kitchen", price: 41000, stock: 20, colors: ["Black", "Silver"], productType: "Appliance", tags: ["coffee", "morning"], imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80" },
  { name: "Stainless Mixing Bowl Set", description: "Set of 5 nesting stainless steel mixing bowls with non-slip bases and pour spouts.", category: "kitchen", price: 15000, stock: 35, colors: ["Silver"], productType: "Prep", tags: ["baking", "cooking"], imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80" },
  { name: "Knife Set 7-Piece", description: "Professional 7-piece German stainless steel knife set with hardwood block.", category: "kitchen", price: 52000, stock: 15, colors: ["Silver/Brown"], productType: "Cutlery", tags: ["chef", "professional"], imageUrl: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80" },

  // ACCESSORIES (10)
  { name: "Handwoven Rattan Tote", description: "Large handwoven rattan tote bag with leather handles and cotton lining.", category: "accessories", price: 23500, stock: 30, colors: ["Natural", "Black"], productType: "Bag", tags: ["summer", "beach", "local"], imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80" },
  { name: "Leather Crossbody Bag", description: "Full-grain leather crossbody with adjustable strap and gold-tone hardware.", category: "accessories", price: 47000, stock: 25, colors: ["Tan", "Black", "Cognac"], productType: "Bag", tags: ["premium", "everyday"], imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80" },
  { name: "Beaded Statement Necklace", description: "Hand-strung Nigerian beaded necklace in vibrant royal colours. Statement piece.", category: "accessories", price: 7500, stock: 50, colors: ["Multi", "Royal Blue", "Green"], productType: "Jewellery", tags: ["cultural", "statement"], imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80" },
  { name: "Gold Cuff Bracelet", description: "Hammered 18K gold-plated brass cuff bracelet. Adjustable and hypoallergenic.", category: "accessories", price: 11500, stock: 40, colors: ["Gold", "Silver"], productType: "Jewellery", tags: ["gold", "minimalist"], imageUrl: "https://images.unsplash.com/photo-1573408301185-9519f94815b2?w=800&q=80" },
  { name: "Polarised Aviator Shades", description: "UV400 polarised aviator sunglasses with stainless steel frame and spring hinges.", category: "accessories", price: 19000, stock: 35, colors: ["Gold/Brown", "Silver/Grey", "Black"], productType: "Eyewear", tags: ["summer", "fashion"], imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80" },
  { name: "Minimalist Leather Wallet", description: "Slim bifold wallet in full-grain leather with 6 card slots and RFID protection.", category: "accessories", price: 15000, stock: 45, colors: ["Black", "Brown", "Tan"], productType: "Wallet", tags: ["everyday", "gift"], imageUrl: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80" },
  { name: "Aso-oke Head Tie (Gele)", description: "Premium aso-oke fabric gele in celebratory colours. Pre-tied option available.", category: "accessories", price: 8500, stock: 60, colors: ["Gold", "Royal Blue", "Burgundy"], productType: "Head Tie", tags: ["ceremony", "cultural", "aso-ebi"], imageUrl: "https://images.unsplash.com/photo-1596516109370-65e37dbd75b9?w=800&q=80" },
  { name: "Structured Baseball Cap", description: "6-panel structured cotton cap with embroidered Lagos crest and curved brim.", category: "accessories", price: 9000, stock: 55, colors: ["Black", "White", "Navy"], productType: "Hat", tags: ["casual", "streetwear"], imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80" },
  { name: "Canvas Weekend Bag", description: "Heavy-duty waxed canvas duffel bag with leather handles. 40L capacity.", category: "accessories", price: 38000, stock: 20, colors: ["Olive", "Navy", "Black"], productType: "Bag", tags: ["travel", "durable"], imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80" },
  { name: "Stainless Steel Watch", description: "Minimalist stainless steel watch with date window and sapphire crystal glass.", category: "accessories", price: 65000, stock: 15, colors: ["Silver", "Rose Gold", "Black"], productType: "Watch", tags: ["premium", "gift"], imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80" },

  // BEAUTY (10)
  { name: "Shea Butter Moisturiser 500ml", description: "Raw unrefined Nigerian shea butter enriched with vitamin E. Deep moisturises and glows skin.", category: "beauty", price: 7500, stock: 80, colors: [], productType: "Skincare", tags: ["natural", "local", "moisturiser"], imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80" },
  { name: "Black Soap Face Wash", description: "Traditional Yoruba black soap face wash with turmeric and honey. Brightens and clears.", category: "beauty", price: 5500, stock: 70, colors: [], productType: "Skincare", tags: ["local", "natural", "skincare"], imageUrl: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80" },
  { name: "Turmeric Glow Serum", description: "20% vitamin C and turmeric brightening serum for radiant, even-toned skin.", category: "beauty", price: 19500, stock: 40, colors: [], productType: "Skincare", tags: ["brightening", "serum"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80" },
  { name: "SPF 50 Tinted Sunscreen", description: "Lightweight SPF 50+ tinted sunscreen formulated for deeper melanin-rich skin tones.", category: "beauty", price: 14000, stock: 50, colors: ["Light Medium", "Medium", "Dark"], productType: "Suncare", tags: ["SPF", "protection"], imageUrl: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80" },
  { name: "Castor Oil Hair Growth Kit", description: "Jamaican black castor oil kit with scalp massager and hot oil cap. Promotes edges and growth.", category: "beauty", price: 11000, stock: 55, colors: [], productType: "Haircare", tags: ["hair growth", "edges"], imageUrl: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&q=80" },
  { name: "Aloe Vera Gel 300ml", description: "100% pure aloe vera gel. Soothes, hydrates and can be used as a styling gel.", category: "beauty", price: 6500, stock: 75, colors: [], productType: "Skincare", tags: ["soothing", "natural"], imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&q=80" },
  { name: "Long-Stay Matte Lipstick Set", description: "Set of 6 long-wear matte lipsticks in shades curated for African skin tones.", category: "beauty", price: 17500, stock: 45, colors: ["Nude", "Berry", "Wine", "Terracotta", "Plum", "Red"], productType: "Makeup", tags: ["lips", "makeup"], imageUrl: "https://images.unsplash.com/photo-1586495777744-4e6232bf2176?w=800&q=80" },
  { name: "Collagen Jade Roller", description: "Genuine jade facial roller and gua sha set. Reduces puffiness and boosts serum absorption.", category: "beauty", price: 8500, stock: 35, colors: ["Green"], productType: "Tools", tags: ["facial", "anti-aging"], imageUrl: "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?w=800&q=80" },
  { name: "Rose Water Toner Mist", description: "Pure rose water facial toner spray that hydrates and preps skin for moisturiser.", category: "beauty", price: 9000, stock: 60, colors: [], productType: "Skincare", tags: ["toning", "hydration"], imageUrl: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=80" },
  { name: "Perfume Oil Collection", description: "Set of 5 long-lasting concentrated perfume oils. Oud, Amber, Musk, Floral and Citrus.", category: "beauty", price: 22000, stock: 30, colors: [], productType: "Fragrance", tags: ["oud", "fragrance", "gift"], imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=80" },

  // OUTDOOR (10)
  { name: "Camping Dome Tent 4-Person", description: "Waterproof 4-person dome tent with UV protection and easy clip assembly. Great for Nigerian parks.", category: "outdoor", price: 75000, stock: 15, colors: ["Green", "Orange"], productType: "Camping", tags: ["camping", "adventure"], imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80" },
  { name: "Portable Gas Grill", description: "Compact 2-burner propane gas grill with folding legs. Perfect for garden parties and owambe.", category: "outdoor", price: 48000, stock: 20, colors: ["Black/Silver"], productType: "BBQ", tags: ["BBQ", "party"], imageUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80" },
  { name: "60L Hiking Backpack", description: "60L internal frame hiking backpack with rain cover and ventilated back panel.", category: "outdoor", price: 58000, stock: 18, colors: ["Black", "Olive", "Blue"], productType: "Bag", tags: ["hiking", "travel"], imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80" },
  { name: "Folding Camping Chair", description: "Lightweight aluminium camping chair with cup holder and carry bag. Holds up to 150kg.", category: "outdoor", price: 14500, stock: 45, colors: ["Black", "Navy", "Red"], productType: "Furniture", tags: ["camping", "beach"], imageUrl: "https://images.unsplash.com/photo-1562113530-57ba467cea38?w=800&q=80" },
  { name: "Stainless Vacuum Flask 1L", description: "Double-wall vacuum insulated 1L flask keeps drinks cold 24hrs or hot 12hrs.", category: "outdoor", price: 18000, stock: 55, colors: ["Black", "Silver", "Navy"], productType: "Hydration", tags: ["hydration", "travel"], imageUrl: "https://images.unsplash.com/photo-1588613254750-cf8b553e4e85?w=800&q=80" },
  { name: "Solar Camping Lantern", description: "USB rechargeable + solar LED lantern with 4 light modes. Essential for power-cut nights.", category: "outdoor", price: 12500, stock: 40, colors: ["Black", "Yellow"], productType: "Lighting", tags: ["solar", "camping", "essential"], imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80" },
  { name: "Hammock with Tree Straps", description: "Ultralight nylon double hammock with 10ft tree straps. 300kg weight capacity.", category: "outdoor", price: 19500, stock: 30, colors: ["Turquoise/Blue", "Green", "Orange"], productType: "Camping", tags: ["camping", "relaxation"], imageUrl: "https://images.unsplash.com/photo-1567473165935-6e51a9fbf9eb?w=800&q=80" },
  { name: "Cooler Box 30L", description: "Rotomoulded 30L cooler box. Keeps ice for 5 days. Ideal for beach trips and owambe.", category: "outdoor", price: 45000, stock: 15, colors: ["White/Blue", "Black"], productType: "Storage", tags: ["BBQ", "beach", "party"], imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80" },
  { name: "Headlamp 500 Lumens", description: "Rechargeable LED headlamp with 500 lumens, red mode and IPX6 waterproofing.", category: "outdoor", price: 11000, stock: 50, colors: ["Black"], productType: "Lighting", tags: ["hiking", "camping", "essential"], imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80" },
  { name: "Yoga Mat Non-Slip 6mm", description: "Eco-friendly TPE yoga mat with alignment lines and carry strap. 6mm thick.", category: "outdoor", price: 16000, stock: 40, colors: ["Purple", "Black", "Teal"], productType: "Fitness", tags: ["yoga", "fitness", "wellness"], imageUrl: "https://images.unsplash.com/photo-1601925228892-1cf8afa26dc3?w=800&q=80" },

  // BOOKS (10)
  { name: "Things Fall Apart", description: "Chinua Achebe's timeless masterpiece. A cornerstone of African literature. Paperback.", category: "books", price: 4500, stock: 100, colors: [], productType: "Fiction", tags: ["African literature", "classic"], imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80" },
  { name: "Half of a Yellow Sun", description: "Chimamanda Ngozi Adichie's Biafra war saga. A powerful, emotional story of Nigeria.", category: "books", price: 5500, stock: 80, colors: [], productType: "Fiction", tags: ["Nigerian", "historical fiction"], imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80" },
  { name: "The Richest Man in Babylon", description: "Timeless financial wisdom in parables. A must-read for anyone building wealth.", category: "books", price: 4000, stock: 90, colors: [], productType: "Finance", tags: ["money", "wealth", "self-help"], imageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800&q=80" },
  { name: "Atomic Habits", description: "James Clear's global bestseller on building good habits and breaking bad ones.", category: "books", price: 6500, stock: 75, colors: [], productType: "Self-Help", tags: ["habits", "productivity"], imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80" },
  { name: "Purple Hibiscus", description: "Chimamanda's debut novel. A coming-of-age story set in post-colonial Nigeria.", category: "books", price: 5000, stock: 70, colors: [], productType: "Fiction", tags: ["Nigerian", "coming of age"], imageUrl: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&q=80" },
  { name: "Rich Dad Poor Dad", description: "Robert Kiyosaki's personal finance classic. Essential reading for financial independence.", category: "books", price: 5500, stock: 85, colors: [], productType: "Finance", tags: ["money", "investing", "classic"], imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80" },
  { name: "The Art of War", description: "Sun Tzu's ancient text on strategy and leadership. Pocket edition with commentary.", category: "books", price: 3500, stock: 95, colors: [], productType: "Strategy", tags: ["strategy", "leadership", "classic"], imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80" },
  { name: "Lagos: A Cultural History", description: "Deep dive into the history, culture and evolution of Lagos from fishing village to megacity.", category: "books", price: 7000, stock: 40, colors: [], productType: "Non-Fiction", tags: ["Lagos", "history", "Nigeria"], imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80" },
  { name: "Think and Grow Rich", description: "Napoleon Hill's classic on the mindset of wealth and success. Updated edition.", category: "books", price: 5000, stock: 80, colors: [], productType: "Self-Help", tags: ["mindset", "success", "wealth"], imageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80" },
  { name: "We Need New Names", description: "NoViolet Bulawayo's Booker-shortlisted debut. A story of Africa, dreams and displacement.", category: "books", price: 5500, stock: 60, colors: [], productType: "Fiction", tags: ["African literature", "diaspora"], imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80" },

  // TOYS (10)
  { name: "Wooden Building Blocks 100pc", description: "100-piece natural wood building blocks in multiple shapes and colours. Ages 2+.", category: "toys", price: 15000, stock: 35, colors: ["Multi"], productType: "Building", tags: ["educational", "toddler"], imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&q=80" },
  { name: "Remote Control Car 4WD", description: "1:16 scale 4WD off-road RC car with rechargeable battery. 2.4GHz remote. Ages 6+.", category: "toys", price: 22000, stock: 25, colors: ["Red", "Blue", "Green"], productType: "RC Toys", tags: ["RC", "boys"], imageUrl: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&q=80" },
  { name: "Doll House 3-Storey", description: "Wooden 3-storey doll house with 12 furniture pieces. Encourages imaginative play. Ages 3+.", category: "toys", price: 35000, stock: 15, colors: ["Pink/White"], productType: "Dolls", tags: ["girls", "imaginative play"], imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&q=80" },
  { name: "STEM Science Kit Junior", description: "50+ experiment STEM science kit for kids 8-12. Includes lab coat and safety goggles.", category: "toys", price: 18500, stock: 30, colors: ["Multi"], productType: "Educational", tags: ["STEM", "educational", "science"], imageUrl: "https://images.unsplash.com/photo-1532094349884-543559059e2c?w=800&q=80" },
  { name: "Giant Lego-Style Bricks 80pc", description: "Oversized Duplo-compatible soft building bricks. Safe for toddlers. Ages 1.5+.", category: "toys", price: 19000, stock: 30, colors: ["Multi"], productType: "Building", tags: ["toddler", "building"], imageUrl: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&q=80" },
  { name: "Puzzle 500-piece Nigeria Map", description: "Beautiful illustrated 500-piece jigsaw of Nigeria's states, landmarks and culture.", category: "toys", price: 9500, stock: 40, colors: ["Multi"], productType: "Puzzle", tags: ["educational", "Nigeria", "family"], imageUrl: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&q=80" },
  { name: "Board Game: Ayo Olopon", description: "Traditional Yoruba Ayo board game in carved wood. Educational and cultural. Ages 6+.", category: "toys", price: 11000, stock: 45, colors: ["Natural Wood"], productType: "Board Game", tags: ["cultural", "traditional", "family"], imageUrl: "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&q=80" },
  { name: "Art & Craft Set 120pc", description: "120-piece art set with crayons, watercolours, stickers and sketchpad. Ages 5+.", category: "toys", price: 13500, stock: 50, colors: ["Multi"], productType: "Creative", tags: ["art", "creative", "girls", "boys"], imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80" },
  { name: "Soft Plush Elephant", description: "Extra-soft 45cm stuffed elephant in grey plush. Machine washable. Ages 0+.", category: "toys", price: 8000, stock: 60, colors: ["Grey", "Pink"], productType: "Plush", tags: ["baby", "soft toy", "gift"], imageUrl: "https://images.unsplash.com/photo-1567716661677-3ac9f45b8dd8?w=800&q=80" },
  { name: "Electric Piano 61-Key", description: "61-key portable electronic keyboard with 300 tones, USB MIDI and LED display. Ages 5+.", category: "toys", price: 55000, stock: 12, colors: ["Black"], productType: "Musical", tags: ["music", "educational", "piano"], imageUrl: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800&q=80" },
];

async function seed() {
  console.log(`Inserting ${products.length} products...`);
  const rows = products.map(p => ({
    name: p.name,
    description: p.description,
    category: p.category,
    price: p.price,
    currency: "NGN",
    imageUrl: p.imageUrl,
    images: [] as string[],
    colors: p.colors,
    productType: p.productType,
    rating: parseFloat((4.2 + Math.random() * 0.7).toFixed(1)),
    stock: p.stock,
    sellerName: "NowBuy Store",
    tags: p.tags,
  }));
  await db.insert(productsTable).values(rows);
  console.log("Done!");
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
